### PR TITLE
change the logic to create the sample of data in full-text search

### PR DESCRIPTION
**Pull request by liseli**
**Why this PR was created?** 
To fix the issue `Solr query considering only the OCR field return None results`. That happened because, The JSON file used for indexing documents did not contain the OCR field. 

**How the issue was fixed?**
In this PR, a folder with 150 XML files (all public records) was added. All these files were generated by the workflow that indexes documents in Solr, then it contains all the required fields.  A service based on a curl command to index the documents once Solr start up was added to the docker-compose file that use Solr 8.

The docker-compose to start up Solr 6 did not change to make sure we are not change anything in production. If we would need to add a sample of data in our local environment (using babel and Solr 6) we can do it manually.

All the services were tested locally and also using babel.

**How you can test this PR?**

* Download this branch on your local environment
* _Checking Solr 8 in cloud mode_
        *  In your work directory, run the command
               `docker compose -f docker-compose_embedded_zooKeeper.yml up` 
        * To check that Solr is working fine, go to: http://localhost:8983/solr/#/core-x
        * To check if the sample of data was indexed you should see 150 documents in the Solr index
* _Checking Solr 6 in standalone mode_
       * In your work directory run the command 
              `docker-compose -f docker-compose_solr6_standalone.yml up` 
       * To check that Solr is working fine, go to: http://localhost:8983/solr/#/core-x
       * When you query the core-x using Solr admin you should see "response":{"numFound":0,"start":0,"docs":[]} That means, the Solr server contains None documents.
   
Your Solr admin should looks like the image: 
image

### CODE REVIEW

**Review by moseshll — CHANGES_REQUESTED** [review]
The Solr 8 testing went fine, no issues there.
I had trouble with Solr 6 part: if I `cd solr6_standalone` then I get a "file not found" for the subsequent `docker-compose` because docker-compose_solr6_standalone.yml is in the parent directory. When I changed that command to use `-f ../docker-compose_solr6_standalone.yml` (or if cd back up to the parent directory) I get the real issue: "no matching manifest for linux/arm64/v8 in the manifest list entries" which indicates to me Solr 6 isn't available for Mac M1? Not sure if that can be worked around.

**Comment by aelkiss** [comment]
There was a base image that we had working for ARM for solr 6... `solr:6.6.6-alpine` (https://github.com/hathitrust/lss_solr_configs/blob/master/solr6_standalone/Dockerfile#L1) but the docker-compose references `solr:6` ?

**Comment by liseli** [comment]
@moseshll thank you for reviewed this PR. As Aaron mentioned the issue is because in the docker-compose I am using the wrong imagen. I have changed the image in the docker compose (solr:6.6.6-alpine) and right now it is working fine. I have updated the README file and also the instructions to test this PR.

**Review by moseshll — APPROVED** [review]
This change worked for me.

**Review by aelkiss — COMMENTED** [review]
Adding all the sample documents makes the repository very large and take a long time to pull, so I would rather have them somewhere external -- I wonder if we could add these sample documents to a .tar.gz and put them somewhere convenient, and then have the Dockerfile / setup scripts fetch and unpack them?  We could add them as an artifact to a "release" here on github if we wanted to keep them on github, or we could stuff them under www.hathitrust.org, or whatever else is convenient.

**Review by aelkiss — CHANGES_REQUESTED** [review]
I also see a few things in the sample that are not in fact public domain (for example inu.30000004479386), and to really be safe we might want to limit to items that are believed to be public domain worldwide (rights attribute 1 / pd)

**Comment by liseli** [comment]
> Adding all the sample documents makes the repository very large and take a long time to pull, so I would rather have them somewhere external -- I wonder if we could add these sample documents to a .tar.gz and put them somewhere convenient, and then have the Dockerfile / setup scripts fetch and unpack them? We could add them as an artifact to a "release" here on github if we wanted to keep them on github, or we could stuff them under [www.hathitrust.org](http://www.hathitrust.org), or whatever else is convenient.

These recommendation make sense for me, then I will check how to apply it

**Comment by liseli** [comment]
> Adding all the sample documents makes the repository very large and take a long time to pull, so I would rather have them somewhere external -- I wonder if we could add these sample documents to a .tar.gz and put them somewhere convenient, and then have the Dockerfile / setup scripts fetch and unpack them? We could add them as an artifact to a "release" here on github if we wanted to keep them on github, or we could stuff them under [www.hathitrust.org](http://www.hathitrust.org), or whatever else is convenient.

The requested changes were applied and right now the sample of data is in a private repository. After starting up the solr server is necessary to execute some steps to manually index some documents in Solr repository. To test the change you should do:

* *In your work directory, run the command
```docker compose -f docker-compose_embedded_zooKeeper.yml up```
* To check that Solr is working fine, go to: http://localhost:8983/solr/#/core-x, you will see 0 documents in the index.

* **To index the sample of data**,
        *  Download a zip file with a sample of documents to your local environment
                       `scp macc-ht-ingest-000.umdl.umich.edu:/htprep/fulltext_indexing_sample/data_sample.zip ~/datasets` 
* In your working directory,
  * run the script `./indexing_data.sh http://localhost:8983 ~/mydata data_sample.zip`. 
  
Note: The script will extract all the XML files inside the Zip file to a destine folder. Then, it will index the documents in Solr server. The script input parameters are: solr_url, the path to the target folder to extract the files and the path to the zip file.

**Comment by aelkiss** [comment]
I looked at the README and was able to copy the sample data and index documents at least for the solr 8 with embedded zookeper, so I think we're good here. We definitely need to squash commits before merging this one.

**Review by aelkiss — APPROVED** [review]

**Pull request merged**
