### PR TITLE
DEV-661: run lss solr in docker

### PR DESCRIPTION
**Pull request by aelkiss**
Starts, core loads; permissions are hacky (probably gives an error about writing to data directory without manually making it world-writable or owned by the solr user in the docker image with uid 8983).

I am able to index into it from https://github.com/hathitrust/slip/pull/1/files#diff-7729bde77e9cefdfeb697708aff7773828bf5e20da5bd4899542ea041de7b6c5

Questions to consider:

- Are the "admin-extra-html" and solr libraries tracked anywhere else?
- These configs seem to be in use in production, so should we consider removing the dire warning in the README?

### CODE REVIEW

**Comment by aelkiss** [comment]
As mentioned above, there's an irritation here in terms of permissions on the `data` directory since the default solr user is uid 8983. I'm not sure what the best way to handle that is; one way would be to make the data dir world-writable. I'm not sure there's an easy general way to solve the problem, but it's certainly something that comes up frequently.

FYI @moseshll  - I think you might have been dealing with a similar issue on the catalog indexer side?

**Comment by billdueber** [comment]
I don't really understand the permissions problem. What's the downside of have the `data` dir owned by the solr process? Or, say, just putting the solr user in an appropriate `group` or something?

**Comment by aelkiss** [comment]
The issue is that we can't know ahead of time what the user's UID is, and the container may run into permissions issues and/or the user may end up with files with weird permissions that cause issues. I'll see if I can find a way to just run solr with the UID of the user who invokes docker-compose.

**Comment by aelkiss** [comment]
@billdueber Any concerns with the rest of what's here? Did you have any thoughts on the other questions above?
 
> Are the "admin-extra-html" and solr libraries tracked anywhere else?
> These configs seem to be in use in production, so should we consider removing the dire warning in the README?

Thanks!

**Comment by moseshll** [comment]
> FYI @moseshll - I think you might have been dealing with a similar issue on the catalog indexer side?

Yes, it was with catalog indexer but it was because the bind mount (I think that's the term) wanted the `/app` directory owned by root and it caused weirdness when running tests.

**Comment by aelkiss** [comment]
Right. I think the approach I'm going to use (basically running the container as the invoking user) should help in that case too.

**Comment by billdueber** [comment]
This all looks good. The admin-extra* files aren't _needed_, but in solr6 the admin interface will complain if they're not present for each core, and the only way to "fix" it is to go into the jar'd up webapp files to remove the references to them. It was a dumb design decision on their part at the time.

I'd also pull all that nonsense out of the README, as you suggested, since it's been in production longer than most dogs have been alive.  Feel free to edit (or not) the README and then merge.

**Pull request merged**
